-- AUTO-GENERATED by sim.ps1 on 2026-09-21T19:30:21 - do not edit by hand.
PawnSimResults = {
  source = "wowsims-turtle/enhancement_shaman",
  generatedAt = "2026-09-21T19:30:21",
  dps = 0,
  stats = {
  ["Strength"] = 2,
  ["Agility"] = 1.4375,
  ["Intellect"] = 0.3125,
  ["SpellPower"] = 0.1875,
  ["FireSpellDamage"] = 0.1875,
  ["NatureSpellDamage"] = 0,
  ["Mp5"] = 1.875,
  ["SpellHit"] = 1.8124999999999998,
  ["SpellCrit"] = 0.6875,
  ["Ap"] = 1,
  ["Hit"] = 16.4375,
  ["Crit"] = 28.8125,
  ["SpellDamage"] = 0.1875,
  ["MainHandDps"] = 13.75,
  ["TwoHandDps"] = 13.75,
  ["OffHandDps"] = 0,
  ["Haste"] = 22.9375,
  },
}

